version: "2"
services:
  node:
    build: "./"
    restart: always
    volumes:
      - ./frontend:/frontend
      - ./api:/api
    depends_on:
      - couchdb
    expose:
      - "8080"
      - "5000"
    networks: 
      - webappnetwork
  nginx:
    image         : nginx:stable
    container_name: Nginx
    build         : ./nginx
    links         :
      - node
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - webappnetwork
  couchdb:
    image: couchdb
    build: ./couchdb
    ports:
      - "5984:5984"
      - "5986:5986"
    networks: 
      - webappnetwork
networks:
    webappnetwork:
        driver: bridge
